planning_pipelines:
  pipelines_names: ["ompl"]

plan_request_params:
  planer_id: ompl
  planning_attempts: 1
  planning_pipeline: ompl
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0
